version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wolfchatter
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./wolfchatter-backend
    ports:
      - 4000:4000
    environment:
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DB: wolfchatter
      PG_HOST: db
      PG_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./wolfchatter-frontend
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  db-data: