version: '3'
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      PG_USER: postgres
      PG_PASSWORD: password
      PG_DB: wolfchatter
      PG_HOST: db
      PG_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wolfchatter
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: